server:
  port: 8006
spring:
  application:
    name: generate-credit-card-application-service
  datasource:
    url: jdbc:mysql://${MSQL_HOSTNAME:localhost}:${MSQL_PORT:3306}/${MSQL_DB_NAME:cc_details}
    username: ${MSQL_USERNAME:root}
    password: ${MSQL_PASSWORD:root}
  jpa:
    generate-ddl: true
    show-sql: false
  cloud:
    stream:
      function:
        definition: generateCreditCard
      bindings:
        generateCreditCard-in-0:
          destination: CreditCardVerification
          group: creditCard
