server:
  port: 8006
spring:
  application:
    name: generate-credit-card-application-service
  datasource:
    url: jdbc:mysql://${MSQL_HOSTNAME:localhost}:${MSQL_PORT:3306}/${MSQL_DB_NAME:cc_details}
    username: ${MSQL_USERNAME:root}
    password: ${MSQL_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: false
  cloud:
    stream:
      function:
        definition: generateCreditCard
      bindings:
        generateCreditCard-in-0:
          destination: CreditCardVerification
          group: creditCard
          consumer:
            max-attempts: 1
  rabbitmq:
    host: ${RMQ_HOSTNAME:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}
